
package bingo;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



@SuppressWarnings("serial")
public class mainui extends javax.swing.JFrame {
  
  protected ArrayList<Integer> list = new ArrayList<>();
  protected ArrayList<String> list2 = new ArrayList<>();
  protected logic logic =  new logic();
  protected int incr = 0;
  public mainui() {
    initComponents();
    list = logic.bingoInt();
    init();
  }

  private void init(){
    setLocationRelativeTo(null);
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tabbedpane = new javax.swing.JTabbedPane();
    mainTab = new javax.swing.JPanel();
    numberLabel = new javax.swing.JLabel();
    generateButton = new javax.swing.JButton();
    fiveLabel = new javax.swing.JLabel();
    previous5 = new javax.swing.JLabel();
    fourLabel = new javax.swing.JLabel();
    threeLabel = new javax.swing.JLabel();
    twoLabel = new javax.swing.JLabel();
    oneLabel = new javax.swing.JLabel();
    bingoletterpanel = new javax.swing.JPanel();
    B = new javax.swing.JLabel();
    I = new javax.swing.JLabel();
    N = new javax.swing.JLabel();
    G = new javax.swing.JLabel();
    O = new javax.swing.JLabel();
    bingonumberpanel = new javax.swing.JPanel();
    fiftysix = new javax.swing.JLabel();
    fiftyseven = new javax.swing.JLabel();
    fiftytwo = new javax.swing.JLabel();
    sixteen = new javax.swing.JLabel();
    fiftythree = new javax.swing.JLabel();
    seventeen = new javax.swing.JLabel();
    fifty = new javax.swing.JLabel();
    two = new javax.swing.JLabel();
    fiftyone = new javax.swing.JLabel();
    fortyeight = new javax.swing.JLabel();
    fortynine = new javax.swing.JLabel();
    one = new javax.swing.JLabel();
    fiftyfive = new javax.swing.JLabel();
    six = new javax.swing.JLabel();
    fiftyfour = new javax.swing.JLabel();
    five = new javax.swing.JLabel();
    four = new javax.swing.JLabel();
    three = new javax.swing.JLabel();
    fiftyeight = new javax.swing.JLabel();
    sixtytwo = new javax.swing.JLabel();
    sixtyone = new javax.swing.JLabel();
    sixtysix = new javax.swing.JLabel();
    fiftynine = new javax.swing.JLabel();
    sixty = new javax.swing.JLabel();
    twentyfour = new javax.swing.JLabel();
    sixtyfive = new javax.swing.JLabel();
    twentythree = new javax.swing.JLabel();
    sixtyfour = new javax.swing.JLabel();
    twentysix = new javax.swing.JLabel();
    sixtythree = new javax.swing.JLabel();
    twentyfive = new javax.swing.JLabel();
    seventytwo = new javax.swing.JLabel();
    twentytwo = new javax.swing.JLabel();
    twenty = new javax.swing.JLabel();
    nineteen = new javax.swing.JLabel();
    eighteen = new javax.swing.JLabel();
    twentyseven = new javax.swing.JLabel();
    twentyone = new javax.swing.JLabel();
    sixtyeight = new javax.swing.JLabel();
    sixtyseven = new javax.swing.JLabel();
    seventyone = new javax.swing.JLabel();
    seventyfour = new javax.swing.JLabel();
    seventyfive = new javax.swing.JLabel();
    seventy = new javax.swing.JLabel();
    sixtynine = new javax.swing.JLabel();
    fortytwo = new javax.swing.JLabel();
    thirtythree = new javax.swing.JLabel();
    seventythree = new javax.swing.JLabel();
    thirtyfour = new javax.swing.JLabel();
    thirtyfive = new javax.swing.JLabel();
    twentynine = new javax.swing.JLabel();
    thirty = new javax.swing.JLabel();
    thirtyone = new javax.swing.JLabel();
    thirtysix = new javax.swing.JLabel();
    twentyeight = new javax.swing.JLabel();
    thirtytwo = new javax.swing.JLabel();
    twelve = new javax.swing.JLabel();
    eleven = new javax.swing.JLabel();
    eight = new javax.swing.JLabel();
    seven = new javax.swing.JLabel();
    ten = new javax.swing.JLabel();
    nine = new javax.swing.JLabel();
    fortyseven = new javax.swing.JLabel();
    fortythree = new javax.swing.JLabel();
    fortysix = new javax.swing.JLabel();
    fortyone = new javax.swing.JLabel();
    thirtyeight = new javax.swing.JLabel();
    thirtyseven = new javax.swing.JLabel();
    forty = new javax.swing.JLabel();
    thirtynine = new javax.swing.JLabel();
    fortyfour = new javax.swing.JLabel();
    fortyfive = new javax.swing.JLabel();
    fourteen = new javax.swing.JLabel();
    fifteen = new javax.swing.JLabel();
    thirteen = new javax.swing.JLabel();
    restartButton = new javax.swing.JButton();
    SummaryTab = new javax.swing.JPanel();
    menubar = new javax.swing.JMenuBar();
    file = new javax.swing.JMenu();
    exit = new javax.swing.JMenuItem();
    edit = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Bingo Game");
    setResizable(false);

    numberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    numberLabel.setText("Hit Button");
    numberLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    generateButton.setText("Generate");
    generateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        generateButtonActionPerformed(evt);
      }
    });

    fiveLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    fiveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiveLabel.setText("N/A");
    fiveLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    previous5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    previous5.setText("Previous 5");

    fourLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    fourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fourLabel.setText("N/A");
    fourLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    threeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    threeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    threeLabel.setText("N/A");
    threeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    threeLabel.setRequestFocusEnabled(false);

    twoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    twoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twoLabel.setText("N/A");
    twoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    oneLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    oneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    oneLabel.setText("N/A");
    oneLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    B.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
    B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    B.setText("B");

    I.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
    I.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    I.setText("I");

    N.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
    N.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    N.setText("N");

    G.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
    G.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    G.setText("G");

    O.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
    O.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    O.setText("O");

    fiftysix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftysix.setText("56");

    fiftyseven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftyseven.setText("57");

    fiftytwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftytwo.setText("52");

    sixteen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixteen.setText("16");

    fiftythree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftythree.setText("53");

    seventeen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    seventeen.setText("17");

    fifty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fifty.setText("50");

    two.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    two.setText("2");

    fiftyone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftyone.setText("51");

    fortyeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortyeight.setText("48");

    fortynine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortynine.setText("49");

    one.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    one.setText("1");

    fiftyfive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftyfive.setText("55");

    six.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    six.setText("6");

    fiftyfour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftyfour.setText("54");

    five.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    five.setText("5");

    four.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    four.setText("4");

    three.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    three.setText("3");

    fiftyeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftyeight.setText("58");

    sixtytwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtytwo.setText("62");

    sixtyone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtyone.setText("61");

    sixtysix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtysix.setText("66");

    fiftynine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fiftynine.setText("59");

    sixty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixty.setText("60");

    twentyfour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentyfour.setText("24");

    sixtyfive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtyfive.setText("65");

    twentythree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentythree.setText("23");

    sixtyfour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtyfour.setText("64");

    twentysix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentysix.setText("26");

    sixtythree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtythree.setText("63");

    twentyfive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentyfive.setText("25");

    seventytwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    seventytwo.setText("72");

    twentytwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentytwo.setText("22");

    twenty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twenty.setText("20");

    nineteen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nineteen.setText("19");

    eighteen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    eighteen.setText("18");

    twentyseven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentyseven.setText("27");

    twentyone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentyone.setText("21");

    sixtyeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtyeight.setText("68");

    sixtyseven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtyseven.setText("67");

    seventyone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    seventyone.setText("71");

    seventyfour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    seventyfour.setText("74");

    seventyfive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    seventyfive.setText("75");

    seventy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    seventy.setText("70");

    sixtynine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sixtynine.setText("69");

    fortytwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortytwo.setText("42");

    thirtythree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtythree.setText("33");

    seventythree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    seventythree.setText("73");

    thirtyfour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtyfour.setText("34");

    thirtyfive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtyfive.setText("35");

    twentynine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentynine.setText("29");

    thirty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirty.setText("30");

    thirtyone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtyone.setText("31");

    thirtysix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtysix.setText("36");

    twentyeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twentyeight.setText("28");

    thirtytwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtytwo.setText("32");

    twelve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    twelve.setText("12");

    eleven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    eleven.setText("11");

    eight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    eight.setText("8");

    seven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    seven.setText("7");

    ten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ten.setText("10");

    nine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nine.setText("9");

    fortyseven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortyseven.setText("47");

    fortythree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortythree.setText("43");

    fortysix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortysix.setText("46");

    fortyone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortyone.setText("41");

    thirtyeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtyeight.setText("38");

    thirtyseven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtyseven.setText("37");

    forty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    forty.setText("40");

    thirtynine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirtynine.setText("39");

    fortyfour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortyfour.setText("44");

    fortyfive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fortyfive.setText("45");

    fourteen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fourteen.setText("14");

    fifteen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    fifteen.setText("15");

    thirteen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    thirteen.setText("13");

    javax.swing.GroupLayout bingonumberpanelLayout = new javax.swing.GroupLayout(bingonumberpanel);
    bingonumberpanel.setLayout(bingonumberpanelLayout);
    bingonumberpanelLayout.setHorizontalGroup(
      bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bingonumberpanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(bingonumberpanelLayout.createSequentialGroup()
            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(eleven, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(twelve, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(thirteen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fourteen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fifteen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(bingonumberpanelLayout.createSequentialGroup()
            .addComponent(sixteen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(seventeen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(eighteen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(nineteen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(twenty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(twentyone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(twentytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(twentythree, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(twentyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(twentyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(twentysix, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(twentyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(twentyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(twentynine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(thirty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(bingonumberpanelLayout.createSequentialGroup()
            .addComponent(thirtyone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(thirtytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(thirtythree, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(thirtyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(thirtyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(thirtysix, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(thirtyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(thirtyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(thirtynine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(forty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fortyone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fortytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fortythree, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fortyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fortyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(bingonumberpanelLayout.createSequentialGroup()
            .addComponent(fortysix, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fortyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fortyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fortynine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fifty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fiftyone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fiftytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fiftythree, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fiftyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fiftyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fiftysix, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fiftyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fiftyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(fiftynine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(sixty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(bingonumberpanelLayout.createSequentialGroup()
            .addComponent(sixtyone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(sixtytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(sixtythree, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(sixtyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(sixtyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(sixtysix, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(sixtyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(sixtyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(sixtynine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(seventy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(seventyone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(seventytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(seventythree, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(seventyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(seventyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    bingonumberpanelLayout.setVerticalGroup(
      bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bingonumberpanelLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(eleven, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(twelve, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(thirteen, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fourteen, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fifteen, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(26, 26, 26)
        .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(sixteen, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(seventeen, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(eighteen, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(nineteen, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(twenty, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(twentyone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(twentytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(twentythree)
          .addComponent(twentyfour)
          .addComponent(twentyfive)
          .addComponent(twentysix, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(twentyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(twentyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(twentynine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(thirty, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(26, 26, 26)
        .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(thirtyfive)
          .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(thirtyone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(thirtytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(thirtythree, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(thirtyfour)
            .addComponent(thirtysix, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(thirtyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(thirtyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(thirtynine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(forty)
            .addComponent(fortyone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fortytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fortythree, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fortyfour)
            .addComponent(fortyfive)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
        .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(fiftyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(fortysix, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fortyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fortyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fortynine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fifty, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fiftyone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fiftytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fiftythree, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fiftyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fiftyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fiftysix, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fiftyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fiftynine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sixty, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(26, 26, 26)
        .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(sixtysix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(seventyfour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(bingonumberpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(sixtyone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sixtytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sixtythree, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sixtyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sixtyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sixtyseven, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sixtyeight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sixtynine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(seventy, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(seventyone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(seventytwo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(seventythree, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(seventyfive, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(22, 22, 22))
    );

    javax.swing.GroupLayout bingoletterpanelLayout = new javax.swing.GroupLayout(bingoletterpanel);
    bingoletterpanel.setLayout(bingoletterpanelLayout);
    bingoletterpanelLayout.setHorizontalGroup(
      bingoletterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bingoletterpanelLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(bingoletterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(bingonumberpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    bingoletterpanelLayout.setVerticalGroup(
      bingoletterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bingoletterpanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(bingoletterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(bingonumberpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(bingoletterpanelLayout.createSequentialGroup()
            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(11, 11, 11)
            .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(11, 11, 11)
            .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(34, Short.MAX_VALUE))
    );

    restartButton.setText("Restart");
    restartButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        restartButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout mainTabLayout = new javax.swing.GroupLayout(mainTab);
    mainTab.setLayout(mainTabLayout);
    mainTabLayout.setHorizontalGroup(
      mainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainTabLayout.createSequentialGroup()
        .addGroup(mainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(mainTabLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(mainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainTabLayout.createSequentialGroup()
              .addContainerGap()
              .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainTabLayout.createSequentialGroup()
              .addGap(63, 63, 63)
              .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGroup(mainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(mainTabLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bingoletterpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(62, 62, 62))
          .addGroup(mainTabLayout.createSequentialGroup()
            .addGap(60, 60, 60)
            .addComponent(previous5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(fiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(fourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(threeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(twoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(7, 7, 7)
            .addComponent(oneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    mainTabLayout.setVerticalGroup(
      mainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainTabLayout.createSequentialGroup()
        .addGroup(mainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(mainTabLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(mainTabLayout.createSequentialGroup()
            .addComponent(bingoletterpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(mainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(previous5)
              .addComponent(fiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(fourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(threeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(twoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(oneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(71, Short.MAX_VALUE))
    );

    tabbedpane.addTab("Main", mainTab);

    javax.swing.GroupLayout SummaryTabLayout = new javax.swing.GroupLayout(SummaryTab);
    SummaryTab.setLayout(SummaryTabLayout);
    SummaryTabLayout.setHorizontalGroup(
      SummaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 844, Short.MAX_VALUE)
    );
    SummaryTabLayout.setVerticalGroup(
      SummaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 372, Short.MAX_VALUE)
    );

    tabbedpane.addTab("Summary", SummaryTab);

    file.setText("File");

    exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
    exit.setText("Exit");
    exit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitActionPerformed(evt);
      }
    });
    file.add(exit);

    menubar.add(file);

    edit.setText("Edit");
    menubar.add(edit);

    setJMenuBar(menubar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tabbedpane)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tabbedpane, javax.swing.GroupLayout.Alignment.TRAILING)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    dispose();
    setVisible(false);
  }//GEN-LAST:event_exitActionPerformed
    
  protected void alreadyCalled(int i){ 
    switch(i){
      case 1: one.setForeground(Color.red); break;
      case 2: two.setForeground(Color.red); break;
      case 3: three.setForeground(Color.red); break;
      case 4: four.setForeground(Color.red); break;
      case 5: five.setForeground(Color.red); break;
      case 6: six.setForeground(Color.red); break;
      case 7: seven.setForeground(Color.red); break;
      case 8: eight.setForeground(Color.red); break;
      case 9: nine.setForeground(Color.red); break;
      case 10: ten.setForeground(Color.red); break;
      case 11: eleven.setForeground(Color.red); break;
      case 12: twelve.setForeground(Color.red); break;
      case 13: thirteen.setForeground(Color.red); break;
      case 14: fourteen.setForeground(Color.red); break;
      case 15: fifteen.setForeground(Color.red); break;
      case 16: sixteen.setForeground(Color.red); break;
      case 17: seventeen.setForeground(Color.red); break;
      case 18: eighteen.setForeground(Color.red); break;
      case 19: nineteen.setForeground(Color.red); break;
      case 20: twenty.setForeground(Color.red); break;
      case 21: twentyone.setForeground(Color.red); break;
      case 22: twentytwo.setForeground(Color.red); break;
      case 23: twentythree.setForeground(Color.red); break;
      case 24: twentyfour.setForeground(Color.red); break;
      case 25: twentyfive.setForeground(Color.red); break;
      case 26: twentysix.setForeground(Color.red); break;
      case 27: twentyseven.setForeground(Color.red); break;
      case 28: twentyeight.setForeground(Color.red); break;
      case 29: twentynine.setForeground(Color.red); break;
      case 30: thirty.setForeground(Color.red); break;
      case 31: thirtyone.setForeground(Color.red); break;
      case 32: thirtytwo.setForeground(Color.red); break;
      case 33: thirtythree.setForeground(Color.red); break;
      case 34: thirtyfour.setForeground(Color.red); break;
      case 35: thirtyfive.setForeground(Color.red); break;
      case 36: thirtysix.setForeground(Color.red); break;
      case 37: thirtyseven.setForeground(Color.red); break;
      case 38: thirtyeight.setForeground(Color.red); break;
      case 39: thirtynine.setForeground(Color.red); break;
      case 40: forty.setForeground(Color.red); break;
      case 41: fortyone.setForeground(Color.red); break;
      case 42: fortytwo.setForeground(Color.red); break;
      case 43: fortythree.setForeground(Color.red); break;
      case 44: fortyfour.setForeground(Color.red); break;
      case 45: fortyfive.setForeground(Color.red); break;
      case 46: fortysix.setForeground(Color.red); break;
      case 47: fortyseven.setForeground(Color.red); break;
      case 48: fortyeight.setForeground(Color.red); break;
      case 49: fortynine.setForeground(Color.red); break;
      case 50: fifty.setForeground(Color.red); break;
      case 51: fiftyone.setForeground(Color.red); break;
      case 52: fiftytwo.setForeground(Color.red); break;
      case 53: fiftythree.setForeground(Color.red); break;
      case 54: fiftyfour.setForeground(Color.red); break;
      case 55: fiftyfive.setForeground(Color.red); break;
      case 56: fiftysix.setForeground(Color.red); break;
      case 57: fiftyseven.setForeground(Color.red); break;
      case 58: fiftyeight.setForeground(Color.red); break;
      case 59: fiftynine.setForeground(Color.red); break;
      case 60: sixty.setForeground(Color.red); break;
      case 61: sixtyone.setForeground(Color.red); break;
      case 62: sixtytwo.setForeground(Color.red); break;
      case 63: sixtythree.setForeground(Color.red); break;
      case 64: sixtyfour.setForeground(Color.red); break;
      case 65: sixtyfive.setForeground(Color.red); break;
      case 66: sixtysix.setForeground(Color.red); break;
      case 67: sixtyseven.setForeground(Color.red); break;
      case 68: sixtyeight.setForeground(Color.red); break;
      case 69: sixtynine.setForeground(Color.red); break;
      case 70: seventy.setForeground(Color.red); break;
      case 71: seventyone.setForeground(Color.red); break;
      case 72: seventytwo.setForeground(Color.red); break;
      case 73: seventythree.setForeground(Color.red); break;
      case 74: seventyfour.setForeground(Color.red); break;
      case 75: seventyfive.setForeground(Color.red); break;
    }
  }
  private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
    if(incr<76){
      int val = list.get(incr);
      String bingoValue = null;
      char c = logic.bingoChar(val);
      bingoValue = c+""+val;
      numberLabel.setText(bingoValue);
      alreadyCalled(val);
      list2.add(bingoValue);
      if(list2.size()>1){
        fiveLabel.setText(list2.get(list2.size()-2));
        if(list2.size()>2){
          fourLabel.setText(list2.get(list2.size()-3));
          if(list2.size()>3){
          threeLabel.setText(list2.get(list2.size()-4));
            if(list2.size()>4){
            twoLabel.setText(list2.get(list2.size()-5));
              if(list2.size()>5){
                oneLabel.setText(list2.get(list2.size()-6));
              }
            }
          }
        }
      }
      incr++;
    }
    if(incr==76){
        JOptionPane.showMessageDialog(null,"Game Over hit restart\n to play again :)");
      }
  }//GEN-LAST:event_generateButtonActionPerformed

  private void resetValues(){
    fiveLabel.setText("N/A");
    fourLabel.setText("N/A");
    threeLabel.setText("N/A");
    twoLabel.setText("N/A");
    oneLabel.setText("N/A");
    one.setForeground(Color.black); 
    two.setForeground(Color.black); 
    three.setForeground(Color.black); 
    four.setForeground(Color.black); 
    five.setForeground(Color.black); 
    six.setForeground(Color.black); 
    seven.setForeground(Color.black); 
    eight.setForeground(Color.black); 
    nine.setForeground(Color.black); 
    ten.setForeground(Color.black); 
    eleven.setForeground(Color.black); 
    twelve.setForeground(Color.black); 
    thirteen.setForeground(Color.black); 
    fourteen.setForeground(Color.black); 
    fifteen.setForeground(Color.black); 
    sixteen.setForeground(Color.black); 
    seventeen.setForeground(Color.black); 
    eighteen.setForeground(Color.black); 
    nineteen.setForeground(Color.black); 
    twenty.setForeground(Color.black); 
    twentyone.setForeground(Color.black); 
    twentytwo.setForeground(Color.black); 
    twentythree.setForeground(Color.black); 
    twentyfour.setForeground(Color.black); 
    twentyfive.setForeground(Color.black); 
    twentysix.setForeground(Color.black); 
    twentyseven.setForeground(Color.black); 
    twentyeight.setForeground(Color.black); 
    twentynine.setForeground(Color.black); 
    thirty.setForeground(Color.black); 
    thirtyone.setForeground(Color.black); 
    thirtytwo.setForeground(Color.black); 
    thirtythree.setForeground(Color.black); 
    thirtyfour.setForeground(Color.black); 
    thirtyfive.setForeground(Color.black); 
    thirtysix.setForeground(Color.black); 
    thirtyseven.setForeground(Color.black); 
    thirtyeight.setForeground(Color.black); 
    thirtynine.setForeground(Color.black); 
    forty.setForeground(Color.black); 
    fortyone.setForeground(Color.black); 
    fortytwo.setForeground(Color.black); 
    fortythree.setForeground(Color.black); 
    fortyfour.setForeground(Color.black); 
    fortyfive.setForeground(Color.black); 
    fortysix.setForeground(Color.black); 
    fortyseven.setForeground(Color.black); 
    fortyeight.setForeground(Color.black); 
    fortynine.setForeground(Color.black); 
    fifty.setForeground(Color.black); 
    fiftyone.setForeground(Color.black); 
    fiftytwo.setForeground(Color.black); 
    fiftythree.setForeground(Color.black); 
    fiftyfour.setForeground(Color.black); 
    fiftyfive.setForeground(Color.black); 
    fiftysix.setForeground(Color.black); 
    fiftyseven.setForeground(Color.black); 
    fiftyeight.setForeground(Color.black); 
    fiftynine.setForeground(Color.black); 
    sixty.setForeground(Color.black); 
    sixtyone.setForeground(Color.black); 
    sixtytwo.setForeground(Color.black); 
    sixtythree.setForeground(Color.black); 
    sixtyfour.setForeground(Color.black); 
    sixtyfive.setForeground(Color.black); 
    sixtysix.setForeground(Color.black); 
    sixtyseven.setForeground(Color.black); 
    sixtyeight.setForeground(Color.black); 
    sixtynine.setForeground(Color.black); 
    seventy.setForeground(Color.black); 
    seventyone.setForeground(Color.black); 
    seventytwo.setForeground(Color.black); 
    seventythree.setForeground(Color.black); 
    seventyfour.setForeground(Color.black); 
    seventyfive.setForeground(Color.black); 
  }
  private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
    resetValues();
    incr = 0;
    Collections.shuffle(list);
    numberLabel.setText("Hit Button");
    JOptionPane.showMessageDialog(null,"Game has restarted.");
    list2.clear();
  }//GEN-LAST:event_restartButtonActionPerformed

  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel B;
  private javax.swing.JLabel G;
  private javax.swing.JLabel I;
  private javax.swing.JLabel N;
  private javax.swing.JLabel O;
  private javax.swing.JPanel SummaryTab;
  private javax.swing.JPanel bingoletterpanel;
  private javax.swing.JPanel bingonumberpanel;
  private javax.swing.JMenu edit;
  private javax.swing.JLabel eight;
  private javax.swing.JLabel eighteen;
  private javax.swing.JLabel eleven;
  private javax.swing.JMenuItem exit;
  private javax.swing.JLabel fifteen;
  private javax.swing.JLabel fifty;
  private javax.swing.JLabel fiftyeight;
  private javax.swing.JLabel fiftyfive;
  private javax.swing.JLabel fiftyfour;
  private javax.swing.JLabel fiftynine;
  private javax.swing.JLabel fiftyone;
  private javax.swing.JLabel fiftyseven;
  private javax.swing.JLabel fiftysix;
  private javax.swing.JLabel fiftythree;
  private javax.swing.JLabel fiftytwo;
  private javax.swing.JMenu file;
  private javax.swing.JLabel five;
  private javax.swing.JLabel fiveLabel;
  private javax.swing.JLabel forty;
  private javax.swing.JLabel fortyeight;
  private javax.swing.JLabel fortyfive;
  private javax.swing.JLabel fortyfour;
  private javax.swing.JLabel fortynine;
  private javax.swing.JLabel fortyone;
  private javax.swing.JLabel fortyseven;
  private javax.swing.JLabel fortysix;
  private javax.swing.JLabel fortythree;
  private javax.swing.JLabel fortytwo;
  private javax.swing.JLabel four;
  private javax.swing.JLabel fourLabel;
  private javax.swing.JLabel fourteen;
  private javax.swing.JButton generateButton;
  private javax.swing.JPanel mainTab;
  private javax.swing.JMenuBar menubar;
  private javax.swing.JLabel nine;
  private javax.swing.JLabel nineteen;
  private javax.swing.JLabel numberLabel;
  private javax.swing.JLabel one;
  private javax.swing.JLabel oneLabel;
  private javax.swing.JLabel previous5;
  private javax.swing.JButton restartButton;
  private javax.swing.JLabel seven;
  private javax.swing.JLabel seventeen;
  private javax.swing.JLabel seventy;
  private javax.swing.JLabel seventyfive;
  private javax.swing.JLabel seventyfour;
  private javax.swing.JLabel seventyone;
  private javax.swing.JLabel seventythree;
  private javax.swing.JLabel seventytwo;
  private javax.swing.JLabel six;
  private javax.swing.JLabel sixteen;
  private javax.swing.JLabel sixty;
  private javax.swing.JLabel sixtyeight;
  private javax.swing.JLabel sixtyfive;
  private javax.swing.JLabel sixtyfour;
  private javax.swing.JLabel sixtynine;
  private javax.swing.JLabel sixtyone;
  private javax.swing.JLabel sixtyseven;
  private javax.swing.JLabel sixtysix;
  private javax.swing.JLabel sixtythree;
  private javax.swing.JLabel sixtytwo;
  private javax.swing.JTabbedPane tabbedpane;
  private javax.swing.JLabel ten;
  private javax.swing.JLabel thirteen;
  private javax.swing.JLabel thirty;
  private javax.swing.JLabel thirtyeight;
  private javax.swing.JLabel thirtyfive;
  private javax.swing.JLabel thirtyfour;
  private javax.swing.JLabel thirtynine;
  private javax.swing.JLabel thirtyone;
  private javax.swing.JLabel thirtyseven;
  private javax.swing.JLabel thirtysix;
  private javax.swing.JLabel thirtythree;
  private javax.swing.JLabel thirtytwo;
  private javax.swing.JLabel three;
  private javax.swing.JLabel threeLabel;
  private javax.swing.JLabel twelve;
  private javax.swing.JLabel twenty;
  private javax.swing.JLabel twentyeight;
  private javax.swing.JLabel twentyfive;
  private javax.swing.JLabel twentyfour;
  private javax.swing.JLabel twentynine;
  private javax.swing.JLabel twentyone;
  private javax.swing.JLabel twentyseven;
  private javax.swing.JLabel twentysix;
  private javax.swing.JLabel twentythree;
  private javax.swing.JLabel twentytwo;
  private javax.swing.JLabel two;
  private javax.swing.JLabel twoLabel;
  // End of variables declaration//GEN-END:variables
}
